import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";

export default function Home() {
  return (
    <>
      <Head>
        <title>MBKDEV | Home</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex min-h-screen w-full items-center text-dark dark:text-light">
        <Layout className="pt-0">
          <div className="flex w-full items-start justify-between">
            <div className="w-1/2">
              <Image src={profilePic} alt="MBKDEV" className="h-auto w-full" />
            </div>
            <div className="flex w-1/2 flex-col items-center self-center">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design."
                className="!text-left !text-6xl"
              />
              <p className="my-4 text-base font-medium ">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
              <div className="mt-2 flex items-center self-start">
                <Link
                  className="flex  items-center rounded-lg border border-solid border-transparent bg-dark p-2.5 px-6 text-lg font-semibold text-light hover:border-dark hover:bg-light hover:text-dark dark:bg-light dark:text-dark hover:dark:border-light hover:dark:text-light"
                  download={true}
                  href="/dummy.pdf"
                  target="_blank"
                >
                  Resume <LinkArrow className="ml-1 w-6" />
                </Link>
                <Link
                  href="mailto:moubarakkerim@gmail.com"
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute bottom-8 right-8 inline-block w-24">
          <Image src={lightBulb} alt="MBKDEV" className="h-auto w-full" />
        </div>
      </main>
    </>
  );
}
